language: node_js
node_js:
  - "0.8"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt run build-all
env:
  global:
    - secure: "lots-of-seemingly-random-characters"